service: preql

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  timeout: 10

functions:

  list-kinds:
    handler: source/ServerlessHandlers/AWS/listKinds.default
    timeout: 1
    memorySize: 128

  validate-object:
    handler: source/ServerlessHandlers/AWS/validateObject.default
    timeout: 5
    memorySize: 128

  index-objects:
    handler: source/ServerlessHandlers/AWS/indexObjects.default
    timeout: 15
    memorySize: 128

  validate:
    handler: source/ServerlessHandlers/AWS/validate.default
    timeout: 30
    memorySize: 256