service: preql

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  timeout: 10

functions:
  transpile:
    handler: source/ServerlessHandlers/AWS/transpile.default
    timeout: 30
    memorySize: 128