service: preql

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  timeout: 30

functions:

  list-kinds:
    handler: dist/ServerlessHandlers/AWS/listKinds.default
    timeout: 1
    memorySize: 128

  validate-object:
    handler: dist/ServerlessHandlers/AWS/validateObject.default
    timeout: 5
    memorySize: 128

  index-objects:
    handler: dist/ServerlessHandlers/AWS/indexObjects.default
    timeout: 15
    memorySize: 128

  validate:
    handler: dist/ServerlessHandlers/AWS/validate.default
    timeout: 30
    memorySize: 256